import type { Metadata } from 'next'
import './globals.css'
import Header from '@/layout/Header'
import style from '@/app/page.module.css'
import '@/styles/index.scss'
import '@fontsource/roboto/400.css'
import '@fontsource/roboto/500.css'
import '@fontsource/roboto/700.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className={style.container}>
            {children}
        </main>
      </body>
    </html>
  )
}
